import { z } from 'zod';
import { randomBytes } from 'crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';

// One-click install: if JWT_SECRET isn't provided, generate one once and persist it under CONFIG_DIR so sessions
// survive restarts. Lets the app boot with zero secrets configured (a set JWT_SECRET always wins).
function ensureJwtSecret(): string {
  if (process.env.JWT_SECRET) return process.env.JWT_SECRET;
  const dir = process.env.CONFIG_DIR || '/config';
  const file = `${dir}/jwt.secret`;
  try {
    if (existsSync(file)) return readFileSync(file, 'utf8').trim();
    mkdirSync(dir, { recursive: true });
    const secret = randomBytes(48).toString('base64url');
    writeFileSync(file, secret, { mode: 0o600 });
    return secret;
  } catch {
    // eslint-disable-next-line no-console
    console.warn('[env] could not persist a JWT secret; using an ephemeral one (set JWT_SECRET or mount /config)');
    return randomBytes(48).toString('base64url');
  }
}
process.env.JWT_SECRET = ensureJwtSecret();

/**
 * The same trick for the Web Push signing keys, and for the same reason.
 *
 * ⚠️ Push was listed in the README as a feature while being inert on the documented install path. The keys
 * were only ever generated by `scripts/setup.sh`, which is the DEVELOPMENT stack -- so anyone following the
 * two-command install got `VAPID_PUBLIC_KEY=` empty, `pushEnabled()` false, and a notifications card that
 * returns null rather than explaining itself. The feature was real and unreachable.
 *
 * Generated once and persisted beside the JWT secret, so a subscription made today still verifies tomorrow.
 * Explicitly-set keys always win, which is what lets an operator keep the pair they already have.
 */
function ensureVapidKeys(): { publicKey: string; privateKey: string } | null {
  if (process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY) {
    return { publicKey: process.env.VAPID_PUBLIC_KEY, privateKey: process.env.VAPID_PRIVATE_KEY };
  }
  const dir = process.env.CONFIG_DIR || '/config';
  const file = `${dir}/vapid.json`;
  try {
    if (existsSync(file)) {
      const j = JSON.parse(readFileSync(file, 'utf8'));
      if (j?.publicKey && j?.privateKey) return j;
    }
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const keys = require('web-push').generateVAPIDKeys();
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, JSON.stringify(keys), { mode: 0o600 });
    return keys;
  } catch {
    // A read-only /config, or web-push missing. Push stays off, which is what happened before -- but now it
    // is the exception rather than the default.
    // eslint-disable-next-line no-console
    console.warn('[env] could not generate or persist VAPID keys; push notifications stay disabled');
    return null;
  }
}
const vapid = ensureVapidKeys();
if (vapid) {
  process.env.VAPID_PUBLIC_KEY = vapid.publicKey;
  process.env.VAPID_PRIVATE_KEY = vapid.privateKey;
}

// z.coerce.boolean() is a trap for env vars: it is just Boolean(value), so the STRING "false" comes out true
// and a flag can only ever be turned off by leaving it unset. Read the actual word instead.
const envFlag = (def: boolean) =>
  z
    .string()
    .optional()
    .transform((v) => (v === undefined || v.trim() === '' ? def : /^(1|true|yes|on)$/i.test(v.trim())));

const schema = z.object({
  NODE_ENV: z.string().default('production'),
  PORT: z.coerce.number().default(3000),
  DATABASE_URL: z.string().min(1),
  KOMGA_BASE_URL: z.string().url().default('http://komga:25600'),
  KOMGA_API_KEY: z.string().default(''), // only needed when LIBRARY_BACKEND=komga; owned mode ignores it
  // The Uchiyomi account the Mihon built-in Komga tracker acts as. The tracker has no login of its own —
  // it derives the URL from the manga and sends only a User-Agent — so a credential-less request cannot be
  // tied to a token. Whitelist one username to accept tracker traffic for it: series detail, thumbnail and
  // the two read-progress/tachiyomi endpoints become reachable WITHOUT auth, attributed to this account.
  // Empty = tracker requests are rejected with 401, i.e. Uchiyomi-to-Mihon sync is off. This is a read of
  // reading state plus mark-chapters-read for ONE account, so it is opt-in rather than a default.
  KOMGA_TRACKER_USER: z.string().default(''),
  JWT_SECRET: z.string().min(16),
  // Optional: legacy pre-seed of the admin (base64 argon2 hash). If unset, the first-run web setup creates the
  // admin instead. argon2 hashes contain '$' which breaks compose ${} interpolation -> carried base64-encoded.
  INITIAL_USER_PASSWORD_HASH_B64: z.string().optional(),
  PUBLIC_ORIGIN: z.string().url().default('http://localhost:3000'),
  CACHE_DIR: z.string().default('/cache'),
  CONFIG_DIR: z.string().default('/config'),
  // Optional OIDC / SSO. Everything stays off unless an issuer and client id are set, so an install that
  // doesn't want it is unaffected. There is no refresh handling on purpose: we mint our own session at the
  // end of the flow and the IdP is only consulted at login.
  OIDC_ISSUER: z.string().default(''),
  OIDC_CLIENT_ID: z.string().default(''),
  OIDC_CLIENT_SECRET: z.string().default(''),
  OIDC_NAME: z.string().default('SSO'),
  OIDC_SCOPES: z.string().default('openid profile email'),
  // Create an account the first time an unknown person signs in through the IdP.
  OIDC_ALLOW_SIGNUP: envFlag(false),
  // Adopt an existing local account whose username matches the one the IdP reports. Off by default: turning
  // it on means trusting your IdP to be authoritative over usernames, which is true when you run it yourself.
  OIDC_LINK_BY_USERNAME: envFlag(false),
  // Users in this IdP group become admins here (leave empty to keep roles managed locally).
  OIDC_ADMIN_GROUP: z.string().default(''),
  // Optional Suwayomi server used purely as an extension engine: it runs Mihon/Tachiyomi's Kotlin extensions
  // on the JVM and exposes them over GraphQL. Empty issuer = feature off, exactly like OIDC. Uchiyomi keeps
  // owning the library, reader, downloads and updates; Suwayomi only answers search/chapters/pages.
  SUWAYOMI_URL: z.string().default(''),
  SUWAYOMI_USERNAME: z.string().default(''),
  SUWAYOMI_PASSWORD: z.string().default(''),
  // Suwayomi can expose hundreds of sources; cross-source search fans out to every REGISTERED source, so
  // registration is opt-in per source and additionally capped here.
  SUWAYOMI_MAX_SOURCES: z.coerce.number().int().min(1).max(500).default(25),
  // How many pages of one chapter to fetch from the extension engine at once. The engine sits between us
  // and the site with its own client and its own rate limiting, and its page URLs are local proxy paths,
  // so the quarter-second one-at-a-time pacing that keeps scraped sites from 429ing us was only slowing
  // extension downloads down for nothing (issue #37). Capped at 8: the engine is a JVM sharing the box, and
  // a 429 from it drops the pool to one for the rest of the chapter anyway.
  SUWAYOMI_PAGE_CONCURRENCY: z.coerce.number().int().min(1).max(8).default(4),
  // How long one source gets to answer "what is new" on Discover. This handler was the only one of its
  // siblings with no bound of its own and inherited the adapter's -- 30s for Suwayomi, 95s for a
  // FlareSolverr-backed site -- so a single slow source stalled the whole wall for over a minute. Settable
  // because an operator on a slow link may want more, and because a test cannot afford to wait 8 seconds.
  SOURCE_LATEST_TIMEOUT_MS: z.coerce.number().int().min(100).max(120000).default(8000),
  // How long the admin "test this source" probe gets, end to end. It exercises search -> series -> chapters
  // -> pages, and each of those can reach FlareSolverr's own 95s abort, so the original 30s Promise.race on
  // the add-a-site path was guarding a 380s worst case (four search terms, serially). This is a wall-clock
  // deadline checked BETWEEN stages and between search terms, which is a bound rather than a hope.
  // 45s, not 25s: a solver-fronted source makes four or more sequential requests through FlareSolverr at
  // one to four seconds each, plus a challenge solve. At 25s the healthiest source on one install timed out
  // mid-test, which then cascaded into a confidently wrong "this site is blocking us" verdict.
  SOURCE_TEST_TIMEOUT_MS: z.coerce.number().int().min(1000).max(120000).default(45000),
  // Recognising a series whose folder was renamed or moved, by matching its chapters' content fingerprints.
  //   off    - a moved folder becomes a new series, as it always has
  //   report - work out what it WOULD match and write it to the audit log, change nothing
  //   apply  - actually move the series to its new folder, keeping progress, favourites and covers
  // Defaults to off: a wrong match moves someone's reading progress onto the wrong series, so this is opt-in
  // and 'report' exists so an operator can read the proposed matches before ever trusting it.
  LIBRARY_REMATCH: z.enum(['off', 'report', 'apply']).default('off'),
  VAPID_PUBLIC_KEY: z.string().default(''),
  VAPID_PRIVATE_KEY: z.string().default(''),
  VAPID_SUBJECT: z.string().default('mailto:admin@uchiyomi.com'),
  CACHE_MAX_BYTES: z.coerce.number().default(16 * 1024 * 1024 * 1024),
  BACKUP_DIR: z.string().default('/backups'),
  BACKUP_KEEP: z.coerce.number().int().min(1).max(365).default(14), // nightly dumps to retain
  ACCESS_TTL_SECONDS: z.coerce.number().default(60 * 15),
  REFRESH_TTL_DAYS: z.coerce.number().default(60),
});

type RawEnv = z.infer<typeof schema>;
export type Env = RawEnv & { initialUserPasswordHash: string };

export const env: Env = (() => {
  const parsed = schema.safeParse(process.env);
  if (!parsed.success) {
    // eslint-disable-next-line no-console
    console.error('Invalid environment:', parsed.error.flatten().fieldErrors);
    process.exit(1);
  }
  const initialUserPasswordHash = parsed.data.INITIAL_USER_PASSWORD_HASH_B64
    ? Buffer.from(parsed.data.INITIAL_USER_PASSWORD_HASH_B64, 'base64').toString('utf8')
    : '';
  return { ...parsed.data, initialUserPasswordHash };
})();
